<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expression" nsURI="http://blackbelt.hu/judo/meta/expression"
    nsPrefix="expr">
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericExpression" abstract="true" interface="true"
      eSuperTypes="#//PrimitiveExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalExpression" abstract="true" interface="true"
      eSuperTypes="#//PrimitiveExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringExpression" abstract="true" interface="true"
      eSuperTypes="#//PrimitiveExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnumerationExpression" abstract="true"
      interface="true" eSuperTypes="#//PrimitiveExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectExpression" abstract="true" interface="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionExpression" abstract="true"
      interface="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Lambda" eSuperTypes="#//variable/ObjectVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//LogicalExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterAndCastingType" eType="#//ElementName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectExpression" lowerBound="1"
        eType="#//ObjectExpression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableReference" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerExpression" abstract="true" interface="true"
      eSuperTypes="#//NumericExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalExpression" abstract="true" interface="true"
      eSuperTypes="#//NumericExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="OrderedCollectionExpression" abstract="true"
      interface="true" eSuperTypes="#//CollectionExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveExpression" abstract="true"
      interface="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="NavigationExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="constant" nsURI="http://blackbelt.hu/judo/meta/expression/constant"
      nsPrefix="const">
    <eClassifiers xsi:type="ecore:EClass" name="Constant" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="Number" abstract="true" eSuperTypes="#//constant/Constant #//NumericExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="Integer" eSuperTypes="#//constant/Number #//IntegerExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Decimal" eSuperTypes="#//constant/Number #//DecimalExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Boolean" eSuperTypes="#//constant/Constant #//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//constant/Constant #//StringExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Literal" eSuperTypes="#//constant/Constant #//EnumerationExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="variable" nsURI="http://blackbelt.hu/judo/meta/expression/variable"
      nsPrefix="var">
    <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalVariable" abstract="true" eSuperTypes="#//variable/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringVariable" abstract="true" eSuperTypes="#//variable/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationVariable" abstract="true"
        eSuperTypes="#//variable/Variable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementName" lowerBound="1"
          eType="#//ElementName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectVariable" abstract="true" eSuperTypes="#//variable/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionVariable" abstract="true"
        eSuperTypes="#//variable/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable" abstract="true" eSuperTypes="#//variable/Variable"/>
    <eClassifiers xsi:type="ecore:EClass" name="DecimalVariable" abstract="true" eSuperTypes="#//variable/Variable"/>
  </eSubpackages>
  <eSubpackages name="operator" nsURI="http://blackbelt.hu/judo/meta/expression/operator"
      nsPrefix="op">
    <eClassifiers xsi:type="ecore:EEnum" name="StringComparator">
      <eLiterals name="lessThan" literal="&lt;"/>
      <eLiterals name="greaterThan" value="1" literal=">"/>
      <eLiterals name="lessOrEqual" value="2" literal="&lt;="/>
      <eLiterals name="greaterOrEqual" value="3" literal=">="/>
      <eLiterals name="equal" value="4" literal="=="/>
      <eLiterals name="notEqual" value="5" literal="!="/>
      <eLiterals name="matches" value="6" literal="matches"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LogicalOperator">
      <eLiterals name="or" literal="or"/>
      <eLiterals name="and" value="1" literal="and"/>
      <eLiterals name="xor" value="2" literal="xor"/>
      <eLiterals name="implies" value="3" literal="implies"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ObjectSelector">
      <eLiterals name="head" value="8"/>
      <eLiterals name="tail" value="9" literal="tail"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="IntegerOperator">
      <eLiterals name="add" literal="+"/>
      <eLiterals name="substract" value="1" literal="-"/>
      <eLiterals name="multiply" value="2" literal="*"/>
      <eLiterals name="modulo" value="4" literal="%"/>
      <eLiterals name="divide" value="5" literal="//"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DecimalOperator">
      <eLiterals name="add" literal="+"/>
      <eLiterals name="substract" value="1" literal="-"/>
      <eLiterals name="multiply" value="2" literal="*"/>
      <eLiterals name="divide" value="3" literal="/"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="IntegerComparator">
      <eLiterals name="lessThan" literal="&lt;"/>
      <eLiterals name="greaterThan" value="1" literal=">"/>
      <eLiterals name="lessOrEqual" value="2" literal="&lt;="/>
      <eLiterals name="greaterOrEqual" value="3" literal=">="/>
      <eLiterals name="equal" value="4" literal="=="/>
      <eLiterals name="notEqual" value="5" literal="!="/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DecimalComparator">
      <eLiterals name="lessThan" literal="&lt;"/>
      <eLiterals name="greaterThan" value="1" literal=">"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="IntegerAggregator">
      <eLiterals name="min" value="1"/>
      <eLiterals name="max" value="2"/>
      <eLiterals name="sum" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DecimalAggregator">
      <eLiterals name="min" value="1"/>
      <eLiterals name="max" value="2"/>
      <eLiterals name="avg" value="3"/>
      <eLiterals name="sum" value="4"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="numeric" nsURI="http://blackbelt.hu/judo/meta/expression/numeric"
      nsPrefix="n">
    <eClassifiers xsi:type="ecore:EClass" name="CountExpression" eSuperTypes="#//IntegerExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerAritmeticExpression" eSuperTypes="#//NumericExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//IntegerExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//IntegerExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/IntegerOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DecimalAritmeticExpression" eSuperTypes="#//NumericExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//NumericExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//NumericExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/DecimalOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerOppositeExpression" eSuperTypes="#//IntegerExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//IntegerExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DecimalOppositeExpression" eSuperTypes="#//DecimalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//DecimalExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerAttribute" eSuperTypes="#//IntegerExpression #//Attribute"/>
    <eClassifiers xsi:type="ecore:EClass" name="DecimalAttribute" eSuperTypes="#//DecimalExpression #//Attribute"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerAggregatedExpression" eSuperTypes="#//IntegerExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/IntegerAggregator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DecimalAggregatedExpression" eSuperTypes="#//DecimalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/DecimalAggregator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerVariableReference" eSuperTypes="#//IntegerExpression #//VariableReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//variable/IntegerVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DecimalVariableReference" eSuperTypes="#//DecimalExpression #//VariableReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//variable/DecimalVariable"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="logical" nsURI="http://blackbelt.hu/judo/meta/expression/logical"
      nsPrefix="l">
    <eClassifiers xsi:type="ecore:EClass" name="StringComparison" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/StringComparator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationComparison" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//EnumerationExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//EnumerationExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/IntegerComparator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NegationExpression" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//LogicalExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="KleeneExpression" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//LogicalExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//LogicalExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/LogicalOperator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceOfExpression" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectExpression" lowerBound="1"
          eType="#//ObjectExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementName" lowerBound="1"
          eType="#//ElementName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalAttribute" eSuperTypes="#//LogicalExpression #//Attribute"/>
    <eClassifiers xsi:type="ecore:EClass" name="UndefinedAttributeComparison" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectExpression" lowerBound="1"
          eType="#//ObjectExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UndefinedNavigationComparison" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectExression" lowerBound="1"
          eType="#//ObjectExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogicalVariableReference" eSuperTypes="#//LogicalExpression #//VariableReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//variable/LogicalVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContainsExpression" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectExpression" lowerBound="1"
          eType="#//ObjectExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerComparison" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//IntegerExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//IntegerExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/IntegerComparator"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DecimalComparison" eSuperTypes="#//LogicalExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//NumericExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//NumericExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/DecimalComparator"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="string" nsURI="http://blackbelt.hu/judo/meta/expression/string"
      nsPrefix="str">
    <eClassifiers xsi:type="ecore:EClass" name="StringAttribute" eSuperTypes="#//StringExpression #//Attribute"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringVariableReference" eSuperTypes="#//StringExpression #//VariableReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//variable/StringVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Concatenate" eSuperTypes="#//StringExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LowerCase" eSuperTypes="#//StringExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UpperCase" eSuperTypes="#//StringExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Length" eSuperTypes="#//IntegerExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubString" eSuperTypes="#//StringExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
          eType="#//IntegerExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="length" lowerBound="1"
          eType="#//IntegerExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Position" eSuperTypes="#//IntegerExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containment" lowerBound="1"
          eType="#//StringExpression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Replace" eSuperTypes="#//StringExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//StringExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="replacement" lowerBound="1"
          eType="#//StringExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Trim" eSuperTypes="#//StringExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//StringExpression"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="enumeration" nsURI="http://blackbelt.hu/judo/meta/expression/enumeration"
      nsPrefix="enum">
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationAttribute" eSuperTypes="#//EnumerationExpression #//Attribute"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationVariableReference" eSuperTypes="#//EnumerationExpression #//VariableReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//variable/EnumerationVariable"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="object" nsURI="http://blackbelt.hu/judo/meta/expression/object"
      nsPrefix="o">
    <eClassifiers xsi:type="ecore:EClass" name="ObjectNavigationExpression" eSuperTypes="#//ObjectExpression #//NavigationExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectExpression" lowerBound="1"
          eType="#//ObjectExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectSelectorExpression" eSuperTypes="#//ObjectExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//OrderedCollectionExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
          eType="#//operator/ObjectSelector"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectFilterExpression" eSuperTypes="#//ObjectExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectExpression" lowerBound="1"
          eType="#//ObjectExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filter" lowerBound="1"
          eType="#//Lambda" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectVariableReference" eSuperTypes="#//ObjectExpression #//VariableReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//variable/ObjectVariable"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="collection" nsURI="http://blackbelt.hu/judo/meta/expression/collection"
      nsPrefix="c">
    <eClassifiers xsi:type="ecore:EClass" name="ImmutableCollection" eSuperTypes="#//CollectionExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementName" lowerBound="1"
          eType="#//ElementName"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionFilterExpression" eSuperTypes="#//CollectionExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filter" lowerBound="1"
          eType="#//Lambda" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionVariableReference" eSuperTypes="#//CollectionExpression #//VariableReference">
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//variable/CollectionVariable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionNavigationFromObjectExpression"
        eSuperTypes="#//CollectionExpression #//NavigationExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectExpression" lowerBound="1"
          eType="#//ObjectExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionNavigationFromCollectionExpression"
        eSuperTypes="#//CollectionExpression #//NavigationExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SortExpression" eSuperTypes="#//OrderedCollectionExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="orderBy" lowerBound="1"
          eType="#//collection/OrderBy" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SubCollectionExpression" eSuperTypes="#//OrderedCollectionExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//OrderedCollectionExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//IntegerExpression"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="length" eType="#//IntegerExpression"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderByItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
          eType="#//PrimitiveExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="descending" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderBy" eSuperTypes="#//variable/ObjectVariable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
          eType="#//collection/OrderByItem" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectNavigationFromCollectionExpression"
        eSuperTypes="#//CollectionExpression #//NavigationExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionExpression"
          lowerBound="1" eType="#//CollectionExpression" containment="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
